# Cancellation and Timeouts

## Cancelling coroutine execution

우리는 긴 시간동안 동작하는 백그라운드 코루틴에 대해서 제어해야 할 필요가 있습니다.
예를 들면, 사용자가 코루틴을 시작한 페이지를 닫고 싶어하며, 결과가 더 이상 필요하지 않다면 해당 코루틴을 취소할 수 있습니다.
`launch` 함수는 `job`을 반환하는데, 이를 활용하면 실행중인 코루틴을 종료할 수 있습니다.

```
val job = launch {
    repeat(1000) { i ->
        println("job: I'm sleeping $i ...")
        delay(500L)
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancel() // cancels the job
job.join() // waits for job's completion 
println("main: Now I can quit.")
```

이 코드의 결과는 다음과 같습니다.
```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
main: Now I can quit.
```

`main`이 `job.cancel`을 호출하자마자 취소되었으므로, 다른 코루틴의 값이 출력되지 않습니다.
또한 `cancel`과 `join`을 한 번에 호출하는 `cancelAndJoin`도 존재합니다. 


## Cancellation is cooperative

코루틴의 취소는 조합적으로 작동합니다.
이는 즉, 모든 코틀린 코드는 취소가 가능하도록 조합해야 합니다.
코루틴 내 모든 일시 지연 함수는 취소 가능합니다.
코루틴의 취소 시 발생하는 `CancellationException`을 체크하고 있다는 뜻과 동일합니다.
하지만, 만약 동작 중인 코루틴에서 이러한 취소를 체크할 수 없다면, 코루틴을 취소할 수 없으며, 이예 대한 예시는 다음과 같습니다.


```
val startTime = System.currentTimeMillis()
val job = launch(Dispatchers.Default) {
    var nextPrintTime = startTime
    var i = 0
    while (i < 5) { // computation loop, just wastes CPU
        // print a message twice a second
        if (System.currentTimeMillis() >= nextPrintTime) {
            println("job: I'm sleeping ${i++} ...")
            nextPrintTime += 500L
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

실행 결과는 다음과 같습니다.

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm sleeping 3 ...
job: I'm sleeping 4 ...
main: Now I can quit.
``` 


## Making computation code cancellable

이를 해결하기 위해 코드를 취소 가능하도록 변경하는 방법에는 두 가지가 있습니다.
첫 번째로는 주기적으로 취소 여부를 확인하는 코드를 추가하면 됩니다.
이를 확인하기 위한 가장 좋은 방법으로는 `yield`함수가 있습니다.
그리고 다른 방법으로는 취소 상태를 확인하는 방법이 있습니다.
여기서는 두번째 방법을 사용해보겠습니다.

우리는 이전 코드에서 `while (i < 5)`를 `while (isActive)`로 변경하여 재시작 해보겠습니다.
  
```
val startTime = System.currentTimeMillis()
val job = launch(Dispatchers.Default) {
    var nextPrintTime = startTime
    var i = 0
    while (isActive) { // cancellable computation loop
        // print a message twice a second
        if (System.currentTimeMillis() >= nextPrintTime) {
            println("job: I'm sleeping ${i++} ...")
            nextPrintTime += 500L
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

실행 결과는 다음과 같습니다.

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
main: Now I can quit. 
```

결과를 보듯, 이제 반복문이 정상적으로 종료되었습니다.
`isActive`는 `CoroutineScope` 객체를 통해 코루틴 내에서 사용할 수있는 확장 속성 중 하나입니다. 


## Closing resources with finally

취소 가능한 일시 중단 함수는 취소시 `CancellationException`오류를 발생하며 이는 일반적인 방법으로 처리 할 수 있습니다.
예를 들어 `try {...} finally {...}` 표현식이나 kotlin의 `use` 함수를 사용하는 경우 코루틴 종료 시 실행 될 마지막 코드를 실행할 수 있습니다.

```
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        println("job: I'm running finally")
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

`join`과 `cancelAndJoin` 둘 다 모든 종료 작업이 완료 될 때까지 대기하므로 위의 예제는 다음과 같이 출력됩니다.

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm running finally
main: Now I can quit. 
```


## Run non-cancellable block

만약 이전에 코루틴 종료로 인하여 `finally` 블록으로 들어온 경우에서 일시 중단 함수를 실행하려고 한다면, 문제가 발생합니다.
이를 해결하기 위해서는 `withContext` 함수 및 `NonCancellable` 컨텍스트를 사용하여 `withContext (NonCancellable) {...}`와 같이 활용하려 해결할 수 있습니다.

```
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        withContext(NonCancellable) {
            println("job: I'm running finally")
            delay(1000L)
            println("job: And I've just delayed for 1 sec because I'm non-cancellable")
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

실행 결과는 다음다.과 같습니

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm running finally
job: And I've just delayed for 1 sec because I'm non-cancellable
main: Now I can quit.
```


## Timeout

코루틴을 취소하는 대부분의 이유는 실행 시간의 초과에 대한 것입니다.
이를 위해 `withTimeout`함수를 활용하면 더욱 쉽게 구현할 수 있습니다.

```
withTimeout(1300L) {
    repeat(1000) { i ->
        println("I'm sleeping $i ...")
        delay(500L)
    }
}
```

실행 결과는 다음과 같습니다.

```
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
Exception in thread "main" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1300 ms
```

`withTimeout`에 의해 발생되는 오류인 `TimeoutCancellationException`은 `CancellationException`의 하위 클래스입니다. 
이 때 이전 오류와는 다르게 콘솔에 오류 메시지가 출력되는 것을 볼 수 있습니다.
이는 취소된 코루틴 내부의 `CancellationException`은 코루틴 완료의 정상적인 이유로 간주되기 때문입니다. 

만약 시간 초과에 대해 추가 작업을 수행해야 한다면 해당 코드를 `try {...} catch (e: TimeoutCancellationException) {...}`로 감싸거나,
`withTimeout`과 유사하지만, 오류 대신 `null`을 반환하는 `withTimeoutOrNull`을 사용할 수 있습니다.

```
val result = withTimeoutOrNull(1300L) {
    repeat(1000) { i ->
        println("I'm sleeping $i ...")
        delay(500L)
    }
    "Done" // will get cancelled before it produces this result
}
println("Result is $result")

```

실행 결과는 다음과 같으며, 더 이상 오류 메시지가 뜨지 않는 것을 확인할 수 있습니다.

```
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
Result is null
```  

   
## Asynchronous timeout and resources

https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#asynchronous-timeout-and-resources
